enum RankEnum {
  PVT = 'PVT',
  PV2 = 'PV2',
  PFC = 'PFC',
  SPC = 'SPC',
  CPL = 'CPL',
  SGT = 'SGT',
  SSG = 'SSG',
  SFC = 'SFC',
  MSG = 'MSG',
  CSM = 'CSM',
  WO1 = 'WO1',
  CW2 = 'CW2',
  CW3 = 'CW3',
  CW4 = 'CW4',
  CW5 = 'CW5',
  '2LT' = '2LT',
  '1LT' = '1LT',
  CPT = 'CPT',
  MAJ = 'MAJ',
  LTC = 'LTC',
  COL = 'COL',
  BG = 'BG',
  MG = 'MG',
  LTG = 'LTG',
  GEN = 'GEN',
  CDT = 'CDT',
}
enum FullRankEnum {
  PVT = 'Private',
  PV2 = 'Private',
  PFC = 'Private First Class',
  SPC = 'Specialist',
  CPL = 'Corporal',
  SGT = 'Sergeant',
  SSG = 'Staff Sergeant',
  SFC = 'Sergeant First Class',
  MSG = 'Master Sergeant',
  '1SG' = 'First Sergeant',
  SGM = 'Sergeant Major',
  CSM = 'Command Sergeant Major',
  WO1 = 'Warrant Officer One',
  CW2 = 'Chief Warrant Officer Two',
  CW3 = 'Chief Warrant Officer Three',
  CW4 = 'Chief Warrant Officer Four',
  CW5 = 'Chief Warrant Officer Five',
  '2LT' = 'Second Lieutenant',
  '1LT' = 'First Lieutenant',
  CPT = 'Captain',
  MAJ = 'Major',
  LTC = 'Lieutenant Colonel',
  COL = 'Colonel',
  BG = 'Brigadier General',
  MG = 'Major General',
  LTG = 'Lieutenant General',
  GEN = 'General',
  CDT = 'Cadet',
}

enum PayGrade {
  E1 = 'E-1',
  E2 = 'E-2',
  E3 = 'E-3',
  E4 = 'E-4',
  E5 = 'E-5',
  E6 = 'E-6',
  E7 = 'E-7',
  E8 = 'E-8',
  E9 = 'E-9',
  W1 = 'W-1',
  W2 = 'W-2',
  W3 = 'W-3',
  W4 = 'W-4',
  W5 = 'W-5',
  O1 = 'O-1',
  O2 = 'O-2',
  O3 = 'O-3',
  O4 = 'O-4',
  O5 = 'O-5',
  O6 = 'O-6',
  O7 = 'O-7',
  O8 = 'O-8',
  O9 = 'O-9',
  O10 = 'O-10',
  NONE = 'NONE',
}

enum Insignia {
  NONE = 'NONE',
  PVT = 'PVT_INSIGNIA_URL',
  PV2 = 'PV2_INSIGNIA_URL',
  PFC = 'PFC_INSIGNIA_URL',
  SPC = 'SPC_INSIGNIA_URL',
  CPL = 'CPL_INSIGNIA_URL',
  SGT = 'SGT_INSIGNIA_URL',
  SSG = 'SSG_INSIGNIA_URL',
  SFC = 'SFC_INSIGNIA_URL',
  MSG = 'MSG_INSIGNIA_URL',
  '1SG' = '1SG_INSIGNIA_URL',
  SGM = 'SGM_INSIGNIA_URL',
  WO1 = 'WO1_INSIGNIA_URL',
  CW2 = 'CW2_INSIGNIA_URL',
  CW3 = 'CW3_INSIGNIA_URL',
  CW4 = 'CW4_INSIGNIA_URL',
  CW5 = 'CW5_INSIGNIA_URL',
  '2LT' = '2LT_INSIGNIA_URL',
  '1LT' = '1LT_INSIGNIA_URL',
  CPT = 'CPT_INSIGNIA_URL',
  MAJ = 'MAJ_INSIGNIA_URL',
  LTC = 'LTC_INSIGNIA_URL',
  COL = 'COL_INSIGNIA_URL',
  BG = 'BG_INSIGNIA_URL',
  MG = 'MG_INSIGNIA_URL',
  LTG = 'LTG_INSIGNIA_URL',
  GEN = 'GEN_INSIGNIA_URL',
  CDT = 'CDT_INSIGNIA_URL',
}

enum MPC {
  C = 'C',
  R = 'R',
  O = 'O',
  W = 'W',
  E = 'E',
}

enum MPCFull {
  C = 'Cadet (West Point)',
  R = 'Cadet (ROTC)',
  O = 'Officer',
  W = 'Warrant',
  E = 'Enlisted',
}

enum PayGradeMap {
  E1 = 'E-1',
  E2 = 'E-2',
  E3 = 'E-3',
  E4 = 'E-4',
  E5 = 'E-5',
  E6 = 'E-6',
  E7 = 'E-7',
  E8 = 'E-8',
  E9 = 'E-9',
  W1 = 'W-1',
  W2 = 'W-2',
  W3 = 'W-3',
  W4 = 'W-4',
  W5 = 'W-5',
  O1 = 'O-1',
  O2 = 'O-2',
  O3 = 'O-3',
  O4 = 'O-4',
  O5 = 'O-5',
  O6 = 'O-6',
  O7 = 'O-7',
  O8 = 'O-8',
  O9 = 'O-9',
  O10 = 'O-10',
  NONE = 'NONE',
}

export {
  RankEnum,
  FullRankEnum,
  PayGrade,
  Insignia,
  MPC,
  MPCFull,
  PayGradeMap,
};
